[platform]
soc = "lpc55"
boards = ["nk3xn"]
target = "thumbv8m.main-none-eabi"

[parameters]
flash_origin = 0x00000000
flash_end = 0x92000
filesystem_boundary = 0x93000
filesystem_end = 0x9DE00

[identifier]
usb_id_vendor = 0x20A0
usb_id_product = 0x42B2
usb_manufacturer = "Nitrokey"
usb_product = "Nitrokey 3"
ccid_issuer = "Nitrokey"
