[factory-settings]
debug-access = "Disabled"
rot-fingerprint = "edc1b4db1fd8b09e3ede69620d032ce3cd9865b6062f554d7b45451a49fc7e9e"

[factory-settings.usb-id]
vid = 0x20a0
pid = 0x42dd

[factory-settings.secure-boot-configuration]
puf-enrollment-disabled = true
puf-keycode-generation-disabled = true
dice-computation-disabled = true
secure-boot-enabled = false
use-rsa4096-keys = true
