include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - build
  - deploy

variables:
  #Repo for shared scripts (pull.sh release.sh, nightly_upload.sh):
  GIT_STRATEGY: clone            #This seems to have no effect also set in webinterface
  GIT_DEPTH: 0                    #This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive #This seems to have no effect also set in webinterfac
  SCRIPTS_REPO: git@git.nitrokey.com:nitrokey/gitlab-ci.git
  REPO_GROUP: nitrokey
  REPO_NAME: nitrokey-3-firmware
  MAIN_BRANCH: main 
  IMAGE_NAME: nitrokey3
  COMMON_UPDATE_DOCKER: "true"

build-license-txt:
  image: registry.git.nitrokey.com/nitrokey/nitrokey-3-firmware/nitrokey3:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker
  stage: build
  script:
    - make license.txt
  after_script:
    - mkdir -p artifacts
    - cp license.txt artifacts
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts

build-nk3xn:
  image: registry.git.nitrokey.com/nitrokey/nitrokey-3-firmware/nitrokey3:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker
  stage: build
  script:
    - make -C runners/lpc55 ci BOARD=nk3xn
    - make -C runners/lpc55 ci BOARD=nk3xn PROVISIONER=1
  after_script:
    - mkdir -p artifacts
    - cp ./runners/lpc55/firmware-*.bin artifacts
    - cp ./runners/lpc55/provisioner-*.bin artifacts
    - cp ./runners/lpc55/config/commands.bd artifacts
    - sha256sum artifacts/* | tee artifacts/sha256sum
    - git archive --format zip --output artifacts/nitrokey-3-firmware.zip --prefix nitrokey-3-firmware/ HEAD
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts

build-nk3am:
  image: registry.git.nitrokey.com/nitrokey/nitrokey-3-firmware/nitrokey3:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker
  stage: build
  script:
    - make -C runners/lpc55 ci BOARD=nk3am
    - make -C runners/lpc55 ci BOARD=nk3am PROVISIONER=1
  after_script:
    - mkdir -p artifacts
    - cp ./runners/lpc55/firmware-*.bin artifacts
    - cp ./runners/lpc55/provisioner-*.bin artifacts
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts
