[package]
name = "usbip-runner"
version = { workspace = true }
edition = "2021"

[dependencies]
apps = { path = "../../components/apps", features = ["log-all", "trussed-usbip"] }
cfg-if = { version = "1.0.0" }
clap = { version = "3.0.0", features = ["cargo", "derive"] }
clap-num = "1.0.0"
delog = { version = "0.1.6", features = ["std-log"] }
littlefs2 = { version = "0.4" }
log = { version = "0.4.14", default-features = false }
rand_core = { version = "0.6.4", features = ["getrandom"] }
pretty_env_logger = "0.4.0"
trussed = { version = "0.1", features = ["clients-3"] }
trussed-usbip = { version = "0.0.1", default-features = false, features = ["ctaphid", "ccid"] }
utils = { path = "../../components/utils", features = ["log-all"] }

[features]
test = ["apps/test"]
provisioner = ["apps/provisioner"]
