[package]
name = "utils"
version = { workspace = true }
edition = "2021"

[dependencies]
delog = "0.1"
littlefs2 = "0.3"

[features]
log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[dev-dependencies]
quickcheck = "1.0.3"
