[package]
name = "apps"
version = { workspace = true }
edition = "2021"

[dependencies]
apdu-dispatch = "0.1"
ctaphid-dispatch = "0.1"
trussed = { version = "0.1", features = ["serde-extensions"]}
trussed-usbip = { version = "0.0.1", default-features = false, features = ["ctaphid", "ccid"], optional = true }
usbd-ctaphid = { version = "0.1", optional = true }
utils = { path = "../utils" }

# Backends
trussed-auth = { version = "0.2.2", optional = true }
trussed-rsa-alloc = { version = "0.1.0", optional = true }
trussed-staging = { version = "0.1.0", features = ["wrap-key-to-file", "chunked", "encrypted-chunked"], optional = true }

# apps
admin-app = { version = "0.1.0", optional = true }
fido-authenticator = { version = "0.1.1", features = ["dispatch"], optional = true }
ndef-app = { path = "../ndef-app", optional = true }
oath-authenticator = { version = "0.10.0", features = ["apdu-dispatch", "ctaphid"], optional = true }
opcard = { version = "1.0.0", features = ["apdu-dispatch", "delog", "rsa2048-gen", "rsa4096"], optional = true }
piv-authenticator = { version = "0.2.0", features = ["apdu-dispatch", "delog"], optional = true }
provisioner-app = { path = "../provisioner-app", optional = true }

[features]
default = [
    "admin-app",
    "fido-authenticator",
    "ndef-app",
    "oath-authenticator",
    "opcard",
    "trussed/clients-4",
]
test = ["piv-authenticator", "trussed/clients-5"]
provisioner = ["provisioner-app", "trussed/clients-5"]

# apps
oath-authenticator = ["dep:oath-authenticator", "backend-auth"]
fido-authenticator = ["dep:fido-authenticator", "usbd-ctaphid"]
opcard = ["dep:opcard", "backend-rsa", "backend-auth", "backend-staging"]
piv-authenticator = ["dep:piv-authenticator", "backend-rsa", "backend-auth", "backend-staging"]

# backends
backend-auth = ["trussed-auth"]
backend-rsa = ["trussed-rsa-alloc"]
backend-staging = ["trussed-staging"]

log-all = [
    "admin-app?/log-all",
    "fido-authenticator?/log-all",
    "oath-authenticator?/log-all",
    "opcard?/log-all",
    "provisioner-app?/log-all",
]

# Allow resetting FIDO authenticator (and possibly others) even after 10s uptime
no-reset-time-window = ["fido-authenticator?/disable-reset-time-window"]
